import json
import requests


def main(msg):
    url = "http://localhost:8765/webhook"
    response = requests.post(url, json={"payload": msg})
    print("Response status code:", response.status_code)
    print("Response body:", response.text)


if __name__ == "__main__":
    msg = {
        "id": "False_38379945201791@lid_3AAC8CA420457A103E88",
        "timestamp": 1767081700,
        "from": "38379945201791@lid",
        "fromMe": False,
        "source": "app",
        "to": "972547755011@c.us",
        "body": "בוקר טוב",
        "hasMedia": False,
        "media": None,
        "ack": 1,
        "ackName": "SERVER",
        "location": None,
        "vCards": [],
        "_data": {
            "id": {
                "fromMe": False,
                "remote": "38379945201791@lid",
                "id": "3AAC8CA420457A103E88",
                "_serialized": "False_38379945201791@lid_3AAC8CA420457A103E88"
            },
            "viewed": False,
            "body": "בוקר טוב",
            "type": "chat",
            "t": 1767081700,
            "clientReceivedTsMillis": 1767082252623,
            "notifyName": "Daniella Sassoon",
            "from": "38379945201791@lid",
            "to": "972547755011@c.us",
            "ack": 1,
            "invis": False,
            "isNewMsg": True,
            "star": False,
            "kicNotified": False,
            "recvFresh": True,
            "isFromTemplate": False,
            "isAdsMedia": False,
            "pollInvalidated": False,
            "isSentCagPollCreation": False,
            "latestEditMsgKey": None,
            "latestEditSenderTimestampMs": None,
            "mentionedJidList": [],
            "groupMentions": [],
            "isEventCanceled": False,
            "eventInvalidated": False,
            "isVcardOverMmsDocument": False,
            "isForwarded": False,
            "isQuestion": False,
            "questionReplyQuotedMessage": None,
            "questionResponsesCount": 0,
            "readQuestionResponsesCount": 0,
            "forwardsCount": 0,
            "hasReaction": False,
            "viewMode": "VISIBLE",
            "messageSecret": {
                "0": 108,
                "1": 127,
                "2": 90,
                "3": 0,
                "4": 201,
                "5": 195,
                "6": 219,
                "7": 229,
                "8": 39,
                "9": 138,
                "10": 239,
                "11": 93,
                "12": 143,
                "13": 30,
                "14": 254,
                "15": 40,
                "16": 140,
                "17": 220,
                "18": 33,
                "19": 172,
                "20": 107,
                "21": 197,
                "22": 143,
                "23": 55,
                "24": 9,
                "25": 152,
                "26": 62,
                "27": 105,
                "28": 75,
                "29": 4,
                "30": 41,
                "31": 4
            },
            "productHeaderImageRejected": False,
            "lastPlaybackProgress": 0,
            "isDynamicReplyButtonsMsg": False,
            "isCarouselCard": False,
            "parentMsgId": None,
            "callSilenceReason": None,
            "isVideoCall": False,
            "callDuration": None,
            "callCreator": None,
            "callParticipants": None,
            "isCallLink": None,
            "callLinkToken": None,
            "isMdHistoryMsg": False,
            "stickerSentTs": 0,
            "isAvatar": False,
            "lastUpdateFromServerTs": 0,
            "invokedBotWid": None,
            "bizBotType": None,
            "botResponseTargetId": None,
            "botPluginType": None,
            "botPluginReferenceIndex": None,
            "botPluginSearchProvider": None,
            "botPluginSearchUrl": None,
            "botPluginSearchQuery": None,
            "botPluginMaybeParent": False,
            "botReelPluginThumbnailCdnUrl": None,
            "botMessageDisclaimerText": None,
            "botMsgBodyType": None,
            "reportingTokenInfo": {
                "reportingToken": {
                    "0": 237,
                    "1": 114,
                    "2": 122,
                    "3": 171,
                    "4": 13,
                    "5": 47,
                    "6": 232,
                    "7": 232,
                    "8": 21,
                    "9": 60,
                    "10": 15,
                    "11": 178,
                    "12": 240,
                    "13": 46,
                    "14": 17,
                    "15": 200
                },
                "version": 2,
                "reportingTag": {
                    "0": 1,
                    "1": 14,
                    "2": 162,
                    "3": 107,
                    "4": 229,
                    "5": 126,
                    "6": 30,
                    "7": 99,
                    "8": 216,
                    "9": 222,
                    "10": 105,
                    "11": 30,
                    "12": 163,
                    "13": 34,
                    "14": 205,
                    "15": 38,
                    "16": 248,
                    "17": 34,
                    "18": 162,
                    "19": 41
                }
            },
            "requiresDirectConnection": None,
            "bizContentPlaceholderType": None,
            "hostedBizEncStateMismatch": False,
            "senderOrRecipientAccountTypeHosted": False,
            "placeholderCreatedWhenAccountIsHosted": False,
            "groupHistoryBundleMessageKey": None,
            "groupHistoryBundleMetadata": None,
            "groupHistoryIndividualMessageInfo": None,
            "nonJidMentions": None,
            "links": []
        }
    }

    main(msg)
